const cartTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  REDUCE_CART_ITEM: "REDUCE_CART_ITEM",
  CLEAR_CART: "CLEAR_CART",
  ADD_TO_CART_FROM_DETAIL: "ADD_TO_CART_FROM_DETAIL",
  GET_TOTAL_PRICE: "GET_TOTAL_PRICE",
};
export default cartTypes;
