const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  FETCH_PRODUCT_STARTT: "FETCH_PRODUCT_STARTT",
  SET_PRODUCT: "SET_PRODUCT",
  EDIT_PRODUCT_START: "EDIT_PRODUCT_START",
  PRODUCT_DETAIL_SUCCESS: "PRODUCT_DETAIL_SUCCESS",
  PRODUCT_SORT_BY_SIZE: "PRODUCT_SORT_BY_SIZE",
  PRODUCT_SORT_BY_PRICE: "PRODUCT_SORT_BY_PRICE",
  FETCH_PRODUCT_RELATIVE_START: "FETCH_PRODUCT_RELATIVE_START",
  SET_PRODUCT_RELATIVE: "SET_PRODUCT_RELATIVE",
};
export default productsTypes;
