const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  FETCH_PRODUCT_STARTT: "FETCH_PRODUCT_STARTT",
  SET_PRODUCT: "SET_PRODUCT",
  EDIT_PRODUCT_START: "EDIT_PRODUCT_START",
};
export default productsTypes;
