const ordersTypes = {
  SAVE_ORDER_HISTORY_START: "SAVE_ORDER_HISTORY_START",
  GET_USER_ORDER_HISTORY_START: "GET_USER_ORDER_HISTORY_START",
  SET_USER_ORDER_HISTORY: "SET_USER_ORDER_HISTORY",
  GET_ORDER_DETAILS_START: "GET_ORDER_DETAILS_START",
  SET_ORDER_DETAILS: "SET_ORDER_DETAILS",
  FETCH_ORDER_START: "FETCH_ORDER_START",
  SET_ORDERS: "SET_ORDERS",
  DELETE_ORDER_START: "DELETE_ORDER_START",
  UPDATE_SHIPPING_ORDER_START: "UPDATE_SHIPPING_ORDER_START",
  FETCH_USER_ORDER_START: "FETCH_USER_ORDER_START",
  SET_USER_ORDER: "SET_USER_ORDER",
};
export default ordersTypes;
